version: '3.4'

services:
  database:
    container_name: cursodjango_database
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data:rw
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DATABASE=cursodjango
      - POSTGRES_PASSWORD=pythonpro
      - POSTGRES_USER=pythonpro
    ports:
      - 5434:5432