# Generated by Django 4.0.5 on 2022-06-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='descricao',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modulo',
            name='publico',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
