# Generated by Django 4.0.5 on 2022-06-20 00:09

from django.db import migrations
from django.utils.text import slugify


class Migration(migrations.Migration):

    def preencher_slug_nulo(apps, schema_editor):
        Modulo = apps.get_model("modulos", "Modulo")
        for modulo in Modulo.objects.all():
            modulo.slug = slugify(modulo.titulo)
            modulo.save()

    dependencies = [
        ('modulos', '0003_modulo_slug'),
    ]

    operations = [
        migrations.RunPython(preencher_slug_nulo)
    ]
