# Generated by Django 4.0.5 on 2022-06-25 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0006_aula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={'ordering': ('modulo', 'order')},
        ),
    ]
